apiVersion: v1
kind: PersistentVolume
metadata:
  name: baobao-local-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/local-pv-data
  persistentVolumeReclaimPolicy: Retain