# zookeeper-service yaml file.
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  type: ClusterIP
  selector:
    app: zookeeper-app
  ports:
    - port: 2181
      targetPort: 2181