apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow-web
          image: apache/airflow:2.8.1
          command: ["airflow", "webserver"]
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: airflow-config
        - name: airflow-scheduler
          image: apache/airflow:2.8.1
          command: ["airflow", "scheduler"]
          envFrom:
            - configMapRef:
                name: airflow-config
        - name: airflow-worker
          image: apache/airflow:2.8.1
          command: ["airflow", "celery", "worker"]
          envFrom:
            - configMapRef:
                name: airflow-config