# kafka-service yaml file.
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-external
spec:
  type: NodePort
  selector:
    app: kafka-app
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30092